CREATE TABLE services (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) UNIQUE NOT NULL,
    isActive BOOLEAN DEFAULT FALSE,
    DESCRIPTION TEXT
);

CREATE TABLE subservices (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    serviceID INT UNSIGNED NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    pricePerUnit DECIMAL(10, 2) UNSIGNED NOT NULL,
    UNIQUE KEY uniqueName (serviceID, NAME),
    FOREIGN KEY (serviceID) REFERENCES services(id)
);
